version: "3.8"

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  node_api:
    container_name: api
    build: .
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - "5656:5656"


volumes:
  pgdata:
